# Generated by Django 5.0.6 on 2024-05-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Безымянный проект', max_length=40, verbose_name='Название')),
                ('anons', models.CharField(default='Анонс', max_length=200, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
